Script started on Fri 30 Apr 2021 05:58:34 PM EDT
]0;pakpatel@in-csci-rrpc06:~/OS/Project-4[?1034h[pakpatel@in-csci-rrpc06 Project-4]$ ./cline[K[Kent in-csci-rrpc02:12[K334
h_length = 4
Connected: server's address is in-csci-rrpc02
04/30/21 22:00:25.148390722 UTC: TX: list    list
04/30/21 22:00:25.148390722 UTC: Sent Command: list

04/30/21 22:02:06.823176118 UTC: Header Response Received
04/30/21 22:02:06.823224540 UTC: Status:100  Host:134.68.136.32:1334  Length:522  Type:Text  
	Size		Name
	4096		.
	70		..
	4096		.git
	473		.gitignore
	445		Makefile
	2353		client.c
	39		clientrc
	1297		linked_list.h
	2706		media_transfer.c
	1125		media_transfer.h
	8911		old.c
	9114		parser.c
	2615		parser.h
	1961		queue.h
	9733309		r.mp3
	9733309		received.mp3
	113		send.txt
	9733309		song.mp3
	13312		client.o
	35776		client
	18175		server.c
	34072		server.o
	48904		server
	163		mserver.config
	0		dp_sjf_02_server.script
	0		dp_sjf_03.script
	0		dp_sjf_tesla.script
	12520		media_transfer.o
	18848		parser.o

04/30/21 22:02:06.824861931 UTC: File Listing Received
04/30/21 22:00:25.148390722 UTC: TX: get r.mp3
04/30/21 22:00:25.148390722 UTC: Sent Command: get r.mp3

^C
]0;pakpatel@in-csci-rrpc06:~/OS/Project-4[pakpatel@in-csci-rrpc06 Project-4]$ exit
exit

Script done on Fri 30 Apr 2021 06:07:15 PM EDT
